// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eomnlhqdmjvedihnwnqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvbW5saHFkbWp2ZWRpaG53bnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNjA5MTgsImV4cCI6MjA1MzgzNjkxOH0.pY-Kvz205cDgnIeG2AYighfllBmt069CsVozgyLYSd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);